const invoiceOrderData = [
    {
        id: "ORD-1001",
        invoiceId: "INV-1001",
        product: "Samsung Galaxy F62",
        productId: "PRD-1001",
        category: "Mobile",
        condition: "Good",
        quantity: 1,
        seller: "Rahul Electronics",
        buyer: "ABC Electronics",
        location: "Pune, Maharashtra",
        price: 4500,
        total: 4500,
        status: "Completed",
        paymentStatus: "Paid",
        orderDate: "22 Sep 2026",
        invoiceDate: "22 Sep 2026",
    },

    {
        id: "ORD-1002",
        invoiceId: "INV-1002",
        product: "Dell Inspiron 15",
        productId: "PRD-1002",
        category: "Laptop",
        condition: "Used",
        quantity: 1,
        seller: "Green Tech Recyclers",
        buyer: "Eco Solutions",
        location: "Mumbai, Maharashtra",
        price: 18500,
        total: 18500,
        status: "Processing",
        paymentStatus: "Pending",
        orderDate: "20 Sep 2026",
        invoiceDate: "20 Sep 2026",
    },

    {
        id: "ORD-1003",
        invoiceId: "INV-1003",
        product: "LG LED TV 43 inch",
        productId: "PRD-1003",
        category: "Television",
        condition: "Good",
        quantity: 1,
        seller: "Eco Recycle Ltd.",
        buyer: "Green Electronics",
        location: "Pune, Maharashtra",
        price: 12000,
        total: 12000,
        status: "Completed",
        paymentStatus: "Paid",
        orderDate: "18 Sep 2026",
        invoiceDate: "18 Sep 2026",
    },
];

export default invoiceOrderData;